# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18167026814fa76acf4379560284e5a864ff9c5b79e1cd008afa4a5fada37ab47e6b04282808b73ccbf32389ed87b1f2ded97190059fe1f16383d490b8f0109d

test:
  secret_key_base: f1a78c35d2afb278689246639adbb6862e047c27c32f7d3f96dafeb7ba18375535bb6eb77226463a5030b43106420688e9ad1a07a49557807132e3569c1467e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
